# Generated by Django 2.0 on 2018-08-18 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20180809_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
