# Generated by Django 2.0 on 2018-08-18 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_city_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('user_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'citiesuser',
            },
        ),
    ]
